
const DATA_LOCAIS = [
  {
    "id": "L1-01",
    "nivel": 1,
    "tipo": "NPC",
    "nome": "Mendigo de Cinzas",
    "aparencia": "Homem coberto de fuligem, olhos sempre fechados",
    "encontravel": "Rumor errado sobre o Companheiro",
    "testes": "Carisma CD 10 (Persuasão)",
    "ameacas": "Nenhuma",
    "interacao": "Mente por medo",
    "recompensa": "Informação falsa",
    "custo": "Perda de tempo"
  },
  {
    "id": "L1-02",
    "nivel": 1,
    "tipo": "Local",
    "nome": "Casa com Portas Seladas",
    "aparencia": "Símbolos riscados a giz",
    "encontravel": "Carta incompleta",
    "testes": "Investigação CD 11",
    "ameacas": "Ratos infernais",
    "interacao": "—",
    "recompensa": "Trinket mágico inútil",
    "custo": "Chamar atenção"
  },
  {
    "id": "L1-03",
    "nivel": 1,
    "tipo": "NPC",
    "nome": "Criança Mensageira",
    "aparencia": "Roupa grande demais",
    "encontravel": "Recado cifrado",
    "testes": "Intuição CD 10",
    "ameacas": "—",
    "interacao": "Não entende o conteúdo",
    "recompensa": "Nome de facção",
    "custo": "Informação vaga"
  },
  {
    "id": "L1-04",
    "nivel": 1,
    "tipo": "Evento",
    "nome": "Sussurros no Beco",
    "aparencia": "Vozes sem corpo",
    "encontravel": "Fragmentos de conversa",
    "testes": "Percepção CD 12",
    "ameacas": "Alucinação",
    "interacao": "—",
    "recompensa": "Presságio",
    "custo": "Desvantagem temporária"
  },
  {
    "id": "L1-05",
    "nivel": 1,
    "tipo": "Local",
    "nome": "Poço Seco",
    "aparencia": "Cheiro metálico",
    "encontravel": "Moeda infernal",
    "testes": "Investigação CD 10",
    "ameacas": "Escorregão",
    "interacao": "—",
    "recompensa": "Moeda amaldiçoada",
    "custo": "Marca infernal leve"
  },
  {
    "id": "L2-01",
    "nivel": 2,
    "tipo": "NPC",
    "nome": "Vendedora de Ossos",
    "aparencia": "Carrinho rangente",
    "encontravel": "Boato verdadeiro parcial",
    "testes": "Carisma CD 12",
    "ameacas": "—",
    "interacao": "Cobra caro",
    "recompensa": "Info sobre Zariel",
    "custo": "Ouro"
  },
  {
    "id": "L2-02",
    "nivel": 2,
    "tipo": "Local",
    "nome": "Oficina Queimada",
    "aparencia": "Ferramentas tortas",
    "encontravel": "Arma +0 instável",
    "testes": "Investigação CD 12",
    "ameacas": "Armadilha de fogo (DEX CD 11)",
    "interacao": "—",
    "recompensa": "Arma improvisada",
    "custo": "Quebra fácil"
  },
  {
    "id": "L2-03",
    "nivel": 2,
    "tipo": "Evento",
    "nome": "Execução Pública",
    "aparencia": "Multidão tensa",
    "encontravel": "Documento roubável",
    "testes": "Furtividade CD 12",
    "ameacas": "Diabrete",
    "interacao": "—",
    "recompensa": "Mapa parcial",
    "custo": "Perseguição"
  },
  {
    "id": "L2-04",
    "nivel": 2,
    "tipo": "NPC",
    "nome": "Ex-Hellrider Ferido",
    "aparencia": "Armadura rachada",
    "encontravel": "Pedido de ajuda",
    "testes": "Carisma CD 11",
    "ameacas": "—",
    "interacao": "Missão simples",
    "recompensa": "Favor futuro",
    "custo": "Perigo futuro"
  },
  {
    "id": "L3-01",
    "nivel": 3,
    "tipo": "NPC",
    "nome": "Caldrin, o Sobrevivente",
    "aparencia": "Rosto queimado, olhar firme",
    "encontravel": "Missão: matar um diabo menor",
    "testes": "Carisma CD 13",
    "ameacas": "Espião infernal",
    "interacao": "Negociação difícil",
    "recompensa": "Poção rara",
    "custo": "Inimizade"
  },
  {
    "id": "L3-02",
    "nivel": 3,
    "tipo": "Local",
    "nome": "Casa Assombrada",
    "aparencia": "Frio constante",
    "encontravel": "Espírito preso",
    "testes": "Investigação CD 13",
    "ameacas": "Banshee",
    "interacao": "—",
    "recompensa": "Amuleto mágico",
    "custo": "Trauma"
  },
  {
    "id": "L3-03",
    "nivel": 3,
    "tipo": "Evento",
    "nome": "Procissão Silenciosa",
    "aparencia": "Pessoas vendadas",
    "encontravel": "Informação real",
    "testes": "Religião CD 12",
    "ameacas": "Cultistas",
    "interacao": "—",
    "recompensa": "Nome de Azhkharion",
    "custo": "Atenção"
  },
  {
    "id": "L3-04",
    "nivel": 3,
    "tipo": "NPC",
    "nome": "Mercador das Sombras",
    "aparencia": "Roupas elegantes",
    "encontravel": "Item mágico menor",
    "testes": "Persuasão CD 14",
    "ameacas": "—",
    "interacao": "Troca por favor",
    "recompensa": "Item útil",
    "custo": "Dívida"
  },
  {
    "id": "L4-01",
    "nivel": 4,
    "tipo": "Local",
    "nome": "Arquivo dos Condenados",
    "aparencia": "Correntes e pergaminhos",
    "encontravel": "Contrato infernal",
    "testes": "Investigação CD 14",
    "ameacas": "Armadilha de alma (WIS CD 13)",
    "interacao": "—",
    "recompensa": "Segredo de facção",
    "custo": "Corrupção"
  },
  {
    "id": "L4-02",
    "nivel": 4,
    "tipo": "NPC",
    "nome": "Sacerdotisa da Luz Torta",
    "aparencia": "Aura radiante falsa",
    "encontravel": "Informação crucial",
    "testes": "Intuição CD 14",
    "ameacas": "—",
    "interacao": "Tenta converter",
    "recompensa": "Verdade parcial",
    "custo": "Engano"
  },
  {
    "id": "L4-03",
    "nivel": 4,
    "tipo": "Local",
    "nome": "Torre Caída",
    "aparencia": "Inclinada, instável",
    "encontravel": "Grimório proibido",
    "testes": "Arcana CD 13",
    "ameacas": "Queda / demônios menores",
    "interacao": "—",
    "recompensa": "Magia poderosa",
    "custo": "Maldição"
  },
  {
    "id": "L5-01",
    "nivel": 5,
    "tipo": "NPC",
    "nome": "Informante de Sevariel",
    "aparencia": "Traje militar infernal",
    "encontravel": "Verdade sobre o Companheiro (parcial)",
    "testes": "Persuasão CD 15",
    "ameacas": "Assassinos",
    "interacao": "Negociação tensa",
    "recompensa": "Info real",
    "custo": "Marca infernal"
  },
  {
    "id": "L5-02",
    "nivel": 5,
    "tipo": "Local",
    "nome": "Ponte dos Juramentos",
    "aparencia": "Runas quebradas",
    "encontravel": "Documento estratégico",
    "testes": "Investigação CD 15",
    "ameacas": "Barbed Devil",
    "interacao": "—",
    "recompensa": "Item raro",
    "custo": "Caçada"
  },
  {
    "id": "L5-03",
    "nivel": 5,
    "tipo": "Evento",
    "nome": "Escolta de Prisioneiros",
    "aparencia": "Correntes e gritos",
    "encontravel": "Libertação de NPC",
    "testes": "Furtividade CD 14",
    "ameacas": "Patrulha infernal",
    "interacao": "—",
    "recompensa": "Aliado forte",
    "custo": "Inimigos novos"
  },
  {
    "id": "L1-02",
    "nivel": 1,
    "tipo": "NPC",
    "nome": "Raviel Brasacinza",
    "aparencia": "Tiefling jovem de pele vermelha opaca, chifres serrilhados e roupas simples de couro remendado com um símbolo de Tymora costurado no peito",
    "encontravel": "Praça central, sendo acusado por populares",
    "testes": "Carisma CD 12 (Persuasão ou Intimidação)",
    "ameacas": "Multidão hostil (4 plebeus)",
    "interacao": "Está desesperado e teme ser linchado",
    "recompensa": "Relata movimentações estranhas nos esgotos à noite",
    "custo": "Se ignorado, a tensão racial na cidade aumenta",
    "EXP por Completar": 100
  },
  {
    "id": "L2-01",
    "nivel": 2,
    "tipo": "NPC",
    "nome": "Capitã Helene Marrow",
    "aparencia": "Humana de meia-idade com armadura de cota de malha amassada e capa azul dos Hellriders manchada de fuligem",
    "encontravel": "Quartel improvisado próximo ao mercado",
    "testes": "Carisma CD 13 (Persuasão) ou Sabedoria CD 12 (Intuição)",
    "ameacas": "Guardas desconfiados",
    "interacao": "Acredita que tieflings estejam facilitando invasões demoníacas",
    "recompensa": "Permissão para circular após o toque de recolher",
    "custo": "Se confrontada agressivamente, marca os PJs como suspeitos",
    "EXP por Completar": 150
  },
  {
    "id": "L3-01",
    "nivel": 3,
    "tipo": "NPC",
    "nome": "Darian e Lys Varn",
    "aparencia": "Casal humano pálido; ele veste roupas formais antigas amarrotadas, ela usa vestido simples azul desbotado com aliança prateada",
    "encontravel": "Casa na Rua das Lanternas Quebradas",
    "testes": "Sabedoria CD 14 (Percepção) e Carisma CD 14 (Persuasão)",
    "ameacas": "Manifestação de magia selvagem (Espírito do Ressentimento)",
    "interacao": "Negam que algo esteja errado",
    "recompensa": "Gratidão do casal e pista sobre um dos túneis demoníacos sob a casa",
    "custo": "1 nível de exaustão se enfrentarem a entidade sem descanso",
    "EXP por Completar": 300
  },
  {
    "id": "L4-01",
    "nivel": 4,
    "tipo": "NPC",
    "nome": "Seraphine Umbra",
    "aparencia": "Tiefling de pele violeta e olhos dourados brilhantes, veste mantos negros finos com detalhes prateados e véu cobrindo parte do rosto",
    "encontravel": "Taverna subterrânea chamada Último Sussurro",
    "testes": "Carisma CD 15 (Enganação ou Persuasão)",
    "ameacas": "2 cultistas de Shar ocultos",
    "interacao": "Sabe quem ajudou a roubar o Companheiro",
    "recompensa": "Nome de um dos moradores envolvidos no roubo",
    "custo": "Exige favor futuro ligado à proteção de tieflings",
    "EXP por Completar": 500
  },
  {
    "id": "L5-01",
    "nivel": 5,
    "tipo": "NPC",
    "nome": "Xalruth Karrmoran",
    "aparencia": "Demônio alto de pele carmesim rachada como lava seca, asas mutiladas e armadura orgânica negra pulsante",
    "encontravel": "Câmara central do losango subterrâneo",
    "testes": "Combate direto ou Inteligência CD 16 (Arcana) para sabotar círculo",
    "ameacas": "Legião demoníaca (6 manes + 2 barlguras)",
    "interacao": "Busca atrasar os heróis enquanto a invocação se aproxima",
    "recompensa": "Interrupção de 1 dia no ritual",
    "custo": "Ritual avança mais rápido se falharem",
    "EXP por Completar": 1100
  },
  {
    "id": "L1-03",
    "nivel": 1,
    "tipo": "Local",
    "nome": "Beco das Cinzas Frias",
    "aparencia": "Rua estreita coberta de fuligem constante, janelas fechadas e símbolos riscados nas paredes",
    "encontravel": "Distrito residencial pobre",
    "testes": "Sabedoria CD 11 (Percepção)",
    "ameacas": "Confronto social com moradores preconceituosos",
    "interacao": "Tieflings vivem escondidos aqui",
    "recompensa": "Rumores sobre desaparecimentos recentes",
    "custo": "Hostilidade aberta se provocarem os moradores",
    "EXP por Completar": 75
  },
  {
    "id": "L2-02",
    "nivel": 2,
    "tipo": "Local",
    "nome": "Templo Quebrado de Torm",
    "aparencia": "Colunas rachadas, vitrais estilhaçados e altar coberto por tecido improvisado",
    "encontravel": "Próximo ao centro da cidade",
    "testes": "Inteligência CD 13 (Religião)",
    "ameacas": "Fanáticos acusando tieflings de profanação",
    "interacao": "Discussão pública prestes a virar violência",
    "recompensa": "Aliado entre os fiéis moderados",
    "custo": "Reputação abalada com facção religiosa radical",
    "EXP por Completar": 150
  },
  {
    "id": "L3-02",
    "nivel": 3,
    "tipo": "Local",
    "nome": "Casa Varn",
    "aparencia": "Residência simples de madeira escura, interior frio com manchas de energia arcana nas paredes",
    "encontravel": "Rua das Lanternas Quebradas",
    "testes": "Inteligência CD 14 (Investigação)",
    "ameacas": "Entidade formada por magia selvagem e ressentimento",
    "interacao": "Resolver conflito emocional dissipa a entidade",
    "recompensa": "Entrada secreta para túnel demoníaco",
    "custo": "Dano psíquico contínuo se ignorarem a causa emocional",
    "EXP por Completar": 350
  },
  {
    "id": "L4-02",
    "nivel": 4,
    "tipo": "Local",
    "nome": "Ponta Norte do Losango",
    "aparencia": "Câmara subterrânea circular com runas incandescentes formando metade de um losango no chão",
    "encontravel": "Sob o antigo mercado",
    "testes": "Inteligência CD 15 (Arcana)",
    "ameacas": "Legião demoníaca guardando círculo",
    "interacao": "Sabotar o foco arcano reduz poder da invocação",
    "recompensa": "Atraso parcial do ritual",
    "custo": "Explosão de energia infernal (3d6 fogo)",
    "EXP por Completar": 600
  },
  {
    "id": "L5-02",
    "nivel": 5,
    "tipo": "Local",
    "nome": "Coração do Losango",
    "aparencia": "Grande caverna sob a cidade com quatro túneis convergindo, círculo demoníaco completo pulsando como um coração vermelho",
    "encontravel": "Centro geométrico dos túneis",
    "testes": "Inteligência CD 16 (Arcana) ou Destreza CD 15 (Ferramentas de Ladrão)",
    "ameacas": "Guardas demoníacos e instabilidade planar",
    "interacao": "Destruir um dos focos impede a invocação completa",
    "recompensa": "Impede o demônio maior de atravessar totalmente",
    "custo": "Colapso parcial do túnel",
    "EXP por Completar": 1200
  }
];
